env:
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - react-app
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  no-console: off
globals:
  Cookies: true
  Headers: true
  alert: true
  contract: true
  document: true
  fetch: true
  jasmine: true
  near: true
  nearConfig: true
  nearlib: true
  testSettings: true
  walletAccount: true
  window: true
settings:
  react:
    version: latest
